name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 16 * * *"}]
  workflow_dispatch:
  push: { branches: ["master", "main"] }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: slash9494
          template: classic
          base: header, activity
          config_timezone: Asia/Seoul
          plugin_topics: yes
          plugin_topics_limit: 0
          plugin_topics_mode: icons
          plugin_notable: yes
          plugins_errors_fatal: yes
          plugin_notable_repositories: yes
          plugin_notable_filter: stars:>100
      - uses: actions/checkout@v2
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git pull
          git add -A .
          git commit -m "generated"
          git push

